services:
  web:
    build: ./docker
    ports:
      - "8084:80"
    volumes:
      - ./deployed_site:/var/www/html
    environment:
      - RECAPTCHA_BYPASS=true
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - ENQUIRY_EMAIL=${ENQUIRY_EMAIL}
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
