[build]
  command = "cp deployed_site/index.html.tmpl deployed_site/index.html"
  publish = "deployed_site"

[[redirects]]
  from = "/admin/*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/contact.php"
  to = "/contact-us.html"
  status = 301

[[redirects]]
  from = "/gallery.php"
  to = "/gallery.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
