<?php
// Initiate the autoloader. The file should be generated by Composer.
// You will provide your own autoloader or require the files directly if you did
// not install via Composer.
require_once __DIR__ . '/../vendor/autoload.php';

// Register API keys at https://www.google.com/recaptcha/admin
$siteKey = '6Lc5Jw0UAAAAAETBRcbNldJHFFbsxKN-ZzaN1wiG';
$secret = '6Lc5Jw0UAAAAAKUkceAYCZoaH5Ysd7cxI2GbPoyr';

// reCAPTCHA supported 40+ languages listed here: https://developers.google.com/recaptcha/docs/language
$lang = 'en';
?>
